### ISSUE TITLE
Gradient Boosting TreeをBigQuery MLで動かせるかの検証してほしい

### ISSUE THREAD

**Issue by KUrushi** [na0fu3y/na0fu3y.github.io#20]
TensorFlowのMLモデルの高レベルAPIのEstimator実装にはGradient Boosting Treeの実装がある
EstimatorはBigquery MLで動かすためのSavedModelフォーマットに対応しているので、
BigQuery MLでもGradient Boosting Treeの推論が可能だと思われる

参考資料
[Boosting Trees using Estimators](https://www.tensorflow.org/tutorials/estimator/boosted_trees)
`tf.Estimator.export_saved_model`については[ここ](https://www.tensorflow.org/guide/saved_model#savedmodels_from_estimators)

**Comment by na0fu3y** [comment]
シュッと書いてみました。

https://www.queuery.com/2020/01/29/bigquery-ml-tensorflow-brainfuck.html
#43
