### ISSUE TITLE
NUMERICの意義、使い所を知りたい

### ISSUE THREAD

**Issue by rhoboro** [na0fu3y/na0fu3y.github.io#24]
下記あたりがブログになってたら嬉しいです。

* NUMERICとは
* INTやFLOATとの違い
* NUMERICが適している場面
* （あれば）NUMERICの注意点

**Comment by na0fu3y** [comment]
要望 & アイデアいただき、ありがとうございます。
投稿しました！観点漏れや、物足りない点あれば随時教えてくださいませ。

https://www.queuery.com/bigquery/2020/01/23/numerical-data-types-in-bigquery.html
