### ISSUE TITLE
Stackdriver LoggingとBQシンクの差（料金と検索性、保存期間）を知りたい

### ISSUE THREAD

**Issue by rhoboro** [na0fu3y/na0fu3y.github.io#25]
下記あたりがブログになってたら嬉しいです。

* Stackdriver LoggingからBQシンクする手順
* BQシンクするのがおすすめなログ（GCE、BQあたりのログで？）
* 料金、保存期間の差
* 実例交えたBQシンクの（検索）例
    * 最近の参照テーブルとかいい例だと思う

**Comment by na0fu3y** [comment]
> 保存期間

BigQuery の insert job は Stackdriver Logging で 30 日しか保持されない（insert dataset とかは 400 日のはず）ので、それでサポート体制に影響があるのであれば、ログシンクする必要がありそうですね。

https://cloud.google.com/logging/quotas

**Comment by na0fu3y** [comment]
書いてみたんですが、文章の構成がいまいち読みづらいです。
リンク参照前提の記事だと辛い感じありますが、構成レビューいただけませんか。
https://www.queuery.com/2020/01/28/gcp-logging.html

**Comment by rhoboro** [comment]
勉強になった！
監査ログとそのほかのログの違いですが、アプリケーションが吐くログ(例えばCloudFunctionでprint()とか)って監査ログなんですかね？ 🤔 
意識してStackdriverに書き込んでるわけじゃない気もするけど監査ログではなさそうな気がした。
Stackdriverの画面で見分ける方法があればあると嬉しいかも。

構成はこの方が見やすいかもしれないなと思いました。
ログの表示（自分で書き込んでないという暗黙の前提で）
ログベースの指標
ログの種類（実はここまでのは監査ログで、そのほかに自分でも書き込めるよ）
ログの除外

**Comment by na0fu3y** [comment]
> 監査ログとそのほかのログの違いですが、アプリケーションが吐くログ(例えばCloudFunctionでprint()とか)って監査ログなんですかね？

監査ログではない通常のログのようですね。監査ログは Audit オブジェクトが内包されるため、それで見分けられそうですが、詳しくみたことなかったです。確認します。
https://cloud.google.com/functions/docs/monitoring/logging#writing_logs

> 構成
修正してみます！

**Comment by na0fu3y** [comment]
監査ログのフィルタについて言及されてました。

https://cloud.google.com/blog/products/gcp/best-practices-for-working-with-google-cloud-audit-logging

**Comment by na0fu3y** [comment]
翻訳もありました

https://cloud.google.com/blog/ja/products/gcp/best-practices-for-working-with-google-cloud-audit-logging

**Comment by na0fu3y** [comment]
#39
構成の修正と、監査ログフィルタ、stdout や stderr が通常ログになる点の言及を追加しました。
