### ISSUE TITLE
テーブルの一致判定のクエリを知りたい

### ISSUE THREAD

**Issue by rhoboro** [na0fu3y/na0fu3y.github.io#26]
下記あたりがブログになってたら嬉しいです。

* あるテーブルとあるテーブルの内容が一致することを確認する方法
    * クエリを書き直した際の動作確認などに使いたい
    * クエリとスクリプト間で移植した際の動作確認に使いたい
* 条件付きでもいいので手軽にシュッとできるクエリ
* より広範囲をカバーできるクエリ

**Comment by na0fu3y** [comment]
#36 
テーブル一致判定のクエリに関する記事を追加しました。

**Comment by na0fu3y** [comment]
公開しました
https://www.queuery.com/2020/01/26/two-tables-have-exactly-the-same-data-in-bigquery.html
